# Generated by Django 4.0.5 on 2022-06-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('kakao_id', models.BigIntegerField()),
                ('email', models.CharField(max_length=100, unique=True)),
                ('nick_name', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone_subscribe', models.BooleanField(default=False)),
                ('email_subscribe', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
