# Generated by Django 4.0.5 on 2022-06-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='prodcut',
            new_name='product',
        ),
    ]
